baseURL = "https://harilvfs.github.io/links/"
languageCode = "en"
defaultContentLanguage = "en"

title = "Links"
copyright = "Copy, _right?_ 🤔 | © Hari Chalise"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
name = "Hari Chalise"
headline = "A Linux Enthusiast"
image = "img/author.jpg"  

  links = [
{ email = {href = "mailto:harilvfs@chalisehari.com.np", text = "Mail" } },
{ link = { href = "https://chalisehari.com.np/", text = "Website" } },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { bandcamp = "https://username.bandcamp.com" },
{ bluesky = { href = "https://bsky.app/profile/chalisehari.com.np", text = "Bluesky" } },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
{ discord = { href = "https://discord.com/invite/8NJWstnUHd", text = "Join Discord" } },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
{ github = { href = "https://github.com/harilvfs", text = "GitHub" } },
{ gitlab = { href = "https://gitlab.com/harilvfs", text = "Gitlab" } },
    # { google = "https://www.google.com/" },
    # { instagram = "https://instagram.com/username" },
{ keybase = { href = "https://keybase.io/harilvfs", text = "Keybase" } },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://last.fm/user/username" },
    # { linkedin = "https://linkedin.com/in/username" },
    # { mastodon = "https://mastodon.instance/@username" },
{ medium = { href = "https://medium.com/@aayushchalise", text = "Medium" } },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
{ pinterest = { href = "https://pinterest.com/harilvfs", text = "Pinterest" } },
{ reddit = { href = "https://reddit.com/user/aayush-le", text = "Reddit" } },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { spotify = "https://spotify.com/user/username" },
    # { stack-exchange = "https://stackexchange.com/users/userid/username" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
{ telegram = { href = "https://t.me/harilvfs", text = "Telegram" } },
    # { threads = "https://threads.com/username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
{ twitch = { href = "https://twitch.tv/aayushchalese", text = "Twitch" } },
    # { twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
{ x = { href = "https://x.com/harilvfs", text = "Twitter" } },
{ youtube = { href = "https://youtube.com/@aayushchalese", text = "YouTube" } },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"

